In [1]:
%useLatestDescriptors
%use dataframe, kandy
%use kandy-geo

In [2]:
val df_list = DataFrame.readJson("http://127.0.0.1:7788/nifs/observations/oneday")
df_list.describe()

name,type,count,unique,nulls,top,freq,min,median,max
sta_cde,String,3299,44,0,bgj8a,141,bgj8a,fnm5b,wn087
sta_nam_kor,String,3299,44,0,기장,141,강릉,완도 가교,해남 화산
obs_datetime,String,3299,47,0,2025-03-17 13:00:00,71,2025-03-17 13:00:00,2025-03-18 00:30:00,2025-03-18 12:30:00
repair_gbn,String,3299,1,0,1,3299,1,1,1
obs_lay,String,3299,3,0,1,2058,1,1,3
wtr_tmp,String,3299,79,0,8.9,228,10,7.8,9.9
dox,String?,3299,47,2597,11.9,45,10.1,12.2,9.9
sal,String?,3299,7,3205,34.8,34,32.4,32.6,34.9

In [3]:
val df_code = DataFrame.readJson("http://127.0.0.1:7788/nifs/observatory")
df_code.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,84,84,0,fwdo5,1,null,null,bgj8a,fwdo5,ys002
sta_nam_kor,String,84,80,0,여수,2,null,null,강릉,영광,흑산도 대둔
bld_dat,String,84,64,0,2010-03-14,7,null,null,2003-11-25,2008-07-23,2024-05-13
end_dat,String?,84,38,44,2010-03-15,3,null,null,2005-01-20,2010-03-15,2024-05-25
gru_nam,String,84,3,0,남해,50,null,null,남해,남해,서해
lon,Double,84,84,0,126.736400,1,127.433104,1.137047,124.729500,127.236850,129.813100
lat,Double,84,84,0,34.382500,1,35.182755,1.251893,33.291000,34.741435,38.368100
sur_tmp_yn,String,84,2,0,Y,53,null,null,N,Y,Y
mid_tmp_yn,String,84,2,0,N,61,null,null,N,N,Y
bot_tmp_yn,String,84,2,0,N,75,null,null,N,N,Y
sur_dep,String?,84,11,8,5,48,null,null,1,5,7
mid_dep,String?,84,12,59,6,6,null,null,10,20,9
bot_dep,String?,84,9,71,30,3,null,null,10,25,30
sta_des,String?,84,63,19,태안군청 신규관측소,2,null,null,2020년 7월 4일부로 고성 봉포지역에서 속초 장사항으로 이전설치...,외나로도 남방 국립수산과학원 해양관측부이,포항 구룡포 하정 양식장

In [4]:
val df = df_list.innerJoinWith(df_code.select { sta_cde and gru_nam and lon and lat }) {
    right.sta_cde == sta_cde
}
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3299,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3299,44,0,기장,141,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3299,47,0,2025-03-17 13:00:00,71,null,null,2025-03-17 13:00:00,2025-03-18 00:30:00,2025-03-18 12:30:00
repair_gbn,String,3299,1,0,1,3299,null,null,1,1,1
obs_lay,String,3299,3,0,1,2058,null,null,1,1,3
wtr_tmp,String,3299,79,0,8.9,228,null,null,10,7.8,9.9
dox,String?,3299,47,2597,11.9,45,null,null,10.1,12.2,9.9
sal,String?,3299,7,3205,34.8,34,null,null,32.4,32.6,34.9
sta_cde1,String,3299,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
gru_nam,String,3299,3,0,남해,1703,null,null,남해,남해,서해
lon,Double,3299,44,0,129.227000,141,127.614149,1.175269,124.729500,127.122800,129.549700
lat,Double,3299,44,0,35.187000,141,35.539381,1.377684,33.310400,34.808200,38.368100

In [5]:
df.filter{ gru_nam.equals("동해") and obs_lay.equals("1")  }
    .select{ sta_cde and sta_nam_kor and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [12]:
import kotlinx.datetime.format.FormatStringsInDatetimeFormats
import kotlinx.datetime.format.byUnicodePattern

@OptIn(FormatStringsInDatetimeFormats::class)
val dateTimeFormat = LocalDateTime.Format {
    byUnicodePattern("yyyy-MM-dd HH:mm:ss")
}

val df_East = df.filter {
    gru_nam.equals("동해") and obs_lay.equals("1")
}.add {
    "hour" from obs_datetime.map {
        dateTimeFormat.parse(it).hour
    }
}.select{
    sta_nam_kor and wtr_tmp and obs_datetime  and gru_nam and sta_cde  and "hour"
}.convert { wtr_tmp }.with{ it.toFloat()}


df_East

sta_nam_kor,wtr_tmp,obs_datetime,gru_nam,sta_cde,hour
기장,11.800000,2025-03-17 13:00:00,동해,bgj8a,13
강릉,7.300000,2025-03-17 13:00:00,동해,bgna3,13
삼척,7.800000,2025-03-17 13:00:00,동해,bsc87,13
영덕,11.000000,2025-03-17 13:00:00,동해,byd8a,13
양양,6.300000,2025-03-17 13:00:00,동해,byy87,13
고성 가진,5.600000,2025-03-17 13:00:00,동해,fggo3,13
구룡포 하정,10.700000,2025-03-17 13:00:00,동해,fghe8,13
기장,11.800000,2025-03-17 13:30:00,동해,bgj8a,13
강릉,7.300000,2025-03-17 13:30:00,동해,bgna3,13
삼척,7.800000,2025-03-17 13:30:00,동해,bsc87,13
영덕,11.000000,2025-03-17 13:30:00,동해,byd8a,13
양양,6.200000,2025-03-17 13:30:00,동해,byy87,13
고성 가진,5.500000,2025-03-17 13:30:00,동해,fggo3,13
구룡포 하정,10.700000,2025-03-17 13:30:00,동해,fghe8,13
기장,11.800000,2025-03-17 14:00:00,동해,bgj8a,14
강릉,7.500000,2025-03-17 14:00:00,동해,bgna3,14
삼척,7.700000,2025-03-17 14:00:00,동해,bsc87,14
영덕,11.000000,2025-03-17 14:00:00,동해,byd8a,14
양양,6.400000,2025-03-17 14:00:00,동해,byy87,14
고성 가진,5.400000,2025-03-17 14:00:00,동해,fggo3,14

In [13]:
df_East
    .groupBy { sta_cde and sta_nam_kor and hour }
    .aggregate {
        min{wtr_tmp} into "min"
        max{wtr_tmp} into "max"
        mean{wtr_tmp} into "mean"
        min{obs_datetime} into "time"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 2600 to 1200
        }

        ribbon {
            x("time") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("sta_nam_kor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(sta_nam_kor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("time")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..12.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(sta_nam_kor)
        }
    }

In [14]:
df_East
    .select{  sta_nam_kor and wtr_tmp and obs_datetime   }
    // .convert{ obs_tim }.with{ LocalTime.parse(it) }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 2600 to 600
        }

        x(obs_datetime) { axis.name = "관측일시"}
        y(wtr_tmp) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(sta_nam_kor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [15]:
val df_Current = DataFrame.readJson("http://127.0.0.1:7788/nifs/observations/current")
df_Current.describe()

name,type,count,unique,nulls,top,freq,min,median,max
sta_cde,String,68,42,0,bgj8a,3,bgj8a,fjdfc,wn087
sta_nam_kor,String,68,42,0,기장,3,강릉,영덕,해남 화산
obs_datetime,String,68,1,0,2025-03-18 12:30:00,68,2025-03-18 12:30:00,2025-03-18 12:30:00,2025-03-18 12:30:00
repair_gbn,String,68,1,0,1,68,1,1,1
obs_lay,String,68,3,0,1,42,1,1,3
wtr_tmp,String,68,39,0,8.9,7,10.8,7.7,9.7
dox,String?,68,14,53,10.7,2,10.3,12.1,9.7
sal,String?,68,3,66,34.7,1,32.6,32.6,34.7

In [16]:
val df = df_Current.innerJoinWith(df_code.select { sta_cde and gru_nam and lon and lat }) {
    right.sta_cde == sta_cde
}
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,68,42,0,bgj8a,3,null,null,bgj8a,fjdfc,wn087
sta_nam_kor,String,68,42,0,기장,3,null,null,강릉,영덕,해남 화산
obs_datetime,String,68,1,0,2025-03-18 12:30:00,68,null,null,2025-03-18 12:30:00,2025-03-18 12:30:00,2025-03-18 12:30:00
repair_gbn,String,68,1,0,1,68,null,null,1,1,1
obs_lay,String,68,3,0,1,42,null,null,1,1,3
wtr_tmp,String,68,39,0,8.9,7,null,null,10.8,7.7,9.7
dox,String?,68,14,53,10.7,2,null,null,10.3,12.1,9.7
sal,String?,68,3,66,34.7,1,null,null,32.6,32.6,34.7
sta_cde1,String,68,42,0,bgj8a,3,null,null,bgj8a,fjdfc,wn087
gru_nam,String,68,3,0,남해,34,null,null,남해,남해,서해
lon,Double,68,42,0,129.227000,3,127.626815,1.195191,124.729500,127.415400,129.549700
lat,Double,68,42,0,35.187000,3,35.576290,1.394953,33.310400,34.815200,38.368100

In [19]:
df
    .filter { gru_nam.equals("동해") }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }