In [1]:
%useLatestDescriptors
%use dataframe, kandy
%use kandy-geo
%use lets-plot
%use lets-plot-gt

In [2]:
USE {
    dependencies {
        implementation("org.xerial:sqlite-jdbc:3.49.1.0")
        implementation("ch.qos.logback:logback-classic:1.5.12")
    }
}

In [3]:
import java.sql.Connection
import java.sql.DriverManager

In [4]:
Class.forName("org.sqlite.JDBC")
val connection = DriverManager.getConnection("jdbc:sqlite:/Users/unchil/full-stack-task-manager/full-stack-task-manager.sqlite")

In [24]:
import kotlinx.datetime.*
import kotlinx.datetime.format.*

val now = Clock.System.now()

@OptIn(FormatStringsInDatetimeFormats::class)
val currentTime = now
    .toLocalDateTime(TimeZone.of("Asia/Seoul"))
    .format(LocalDateTime.Format{byUnicodePattern("yyyy-MM-dd HH:mm:ss")})

@OptIn(FormatStringsInDatetimeFormats::class)
val previous24Hour = now
    .minus(24, DateTimeUnit.HOUR)
    .toLocalDateTime(TimeZone.of("Asia/Seoul"))
    .format(LocalDateTime.Format{byUnicodePattern("yyyy-MM-dd HH:mm:ss")})

print("Current time : ${currentTime}, Previous time : ${previous24Hour}")

Current time : 2025-03-27 17:29:53, Previous time : 2025-03-26 17:29:53

In [23]:
import java.time.*
import java.time.format.DateTimeFormatter
import java.text.SimpleDateFormat

val formatter = DateTimeFormatter.ofPattern("YYYY-MM-dd HH:mm:ss")
val now = java.time.LocalDateTime.now()
val prevDay = now.minusHours(24)

print("Current time : ${now.format(formatter)}, Previous time : ${prevDay.format(formatter)}")

Current time : 2025-03-27 17:29:49, Previous time : 2025-03-26 17:29:49

In [25]:
val whereStmt_last24h  = "WHERE obs_datetime >= '${previous24Hour}' "
val sqlStmt = "SELECT * FROM Observation " + whereStmt_last24h
val df_list = DataFrame.readSqlQuery(connection, sqlStmt)
df_list.describe()

name,type,count,unique,nulls,top,freq,min,median,max
sta_cde,String,3330,44,0,bgj8a,141,bgj8a,fnm5b,wn087
sta_nam_kor,String,3330,44,0,기장,141,강릉,완도 가교,해남 화산
obs_dat,String,3330,2,0,2025-03-27,2409,2025-03-26,2025-03-27,2025-03-27
obs_tim,String,3330,47,0,18:00:00,71,00:00:00,11:30:00,23:30:00
repair_gbn,String,3330,1,0,1,3330,1,1,1
obs_lay,String,3330,3,0,1,2061,1,1,3
wtr_tmp,String,3330,93,0,10,195,10,11.8,9.9
dox,String?,3330,51,2625,9.9,51,10,13.2,9.9
sal,String?,3330,8,3236,34.9,33,32.1,32.4,34.9
obs_datetime,String,3330,47,0,2025-03-26 18:00:00,71,2025-03-26 17:30:00,2025-03-27 05:00:00,2025-03-27 16:30:00

In [26]:
val df_code = DataFrame.readSqlTable(connection, "Observatory")
df_code.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,84,84,0,fwdo5,1,null,null,bgj8a,fwdo5,ys002
sta_nam_kor,String,84,80,0,여수,2,null,null,강릉,영광,흑산도 대둔
bld_dat,String,84,64,0,2010-03-14,7,null,null,2003-11-25,2008-07-23,2024-05-13
end_dat,String?,84,38,44,2010-03-15,3,null,null,2005-01-20,2010-03-15,2024-05-25
gru_nam,String,84,3,0,남해,50,null,null,남해,남해,서해
lon,Double,84,84,0,126.736400,1,127.433104,1.137047,124.729500,127.236850,129.813100
lat,Double,84,84,0,34.382500,1,35.182755,1.251893,33.291000,34.741435,38.368100
sur_tmp_yn,String,84,2,0,Y,53,null,null,N,Y,Y
mid_tmp_yn,String,84,2,0,N,61,null,null,N,N,Y
bot_tmp_yn,String,84,2,0,N,75,null,null,N,N,Y
sur_dep,String?,84,11,8,5,48,null,null,1,5,7
mid_dep,String?,84,12,59,6,6,null,null,10,20,9
bot_dep,String?,84,9,71,30,3,null,null,10,25,30
sta_des,String?,84,63,19,태안군청 신규관측소,2,null,null,2020년 7월 4일부로 고성 봉포지역에서 속초 장사항으로 이전설치...,외나로도 남방 국립수산과학원 해양관측부이,포항 구룡포 하정 양식장

In [27]:
val df = df_list.innerJoinWith(df_code.select { sta_cde and gru_nam and lon and lat }) {
    right.sta_cde == sta_cde
}
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3330,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3330,44,0,기장,141,null,null,강릉,완도 가교,해남 화산
obs_dat,String,3330,2,0,2025-03-27,2409,null,null,2025-03-26,2025-03-27,2025-03-27
obs_tim,String,3330,47,0,18:00:00,71,null,null,00:00:00,11:30:00,23:30:00
repair_gbn,String,3330,1,0,1,3330,null,null,1,1,1
obs_lay,String,3330,3,0,1,2061,null,null,1,1,3
wtr_tmp,String,3330,93,0,10,195,null,null,10,11.8,9.9
dox,String?,3330,51,2625,9.9,51,null,null,10,13.2,9.9
sal,String?,3330,8,3236,34.9,33,null,null,32.1,32.4,34.9
obs_datetime,String,3330,47,0,2025-03-26 18:00:00,71,null,null,2025-03-26 17:30:00,2025-03-27 05:00:00,2025-03-27 16:30:00
sta_cde1,String,3330,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
gru_nam,String,3330,3,0,남해,1734,null,null,남해,남해,서해
lon,Double,3330,44,0,129.227000,141,127.619371,1.172931,124.729500,127.122800,129.549700
lat,Double,3330,44,0,35.187000,141,35.532504,1.373708,33.310400,34.808200,38.368100

In [28]:
df.filter{ gru_nam.equals("동해") and obs_lay.equals("1")  }
    .select{ sta_cde and sta_nam_kor and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [29]:
df.filter{ gru_nam.equals("서해") and obs_lay.equals("1")  }
    .select{ sta_cde and sta_nam_kor and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [30]:
df.filter{ gru_nam.equals("남해") and obs_lay.equals("1")  }
    .select{ sta_cde and sta_nam_kor and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [31]:
val df_East = df.filter {
    gru_nam.equals("동해") and obs_lay.equals("1")
}.add {
    "hour" from obs_tim.map {
        LocalTime.parse(it).hour
    }
}.select{
    sta_nam_kor and wtr_tmp and obs_tim  and gru_nam and sta_cde and obs_datetime and "hour"
}.convert { wtr_tmp }.with{ it.toFloat()}


df_East

sta_nam_kor,wtr_tmp,obs_tim,gru_nam,sta_cde,obs_datetime,hour
기장,11.700000,17:30:00,동해,bgj8a,2025-03-26 17:30:00,17
강릉,9.900000,17:30:00,동해,bgna3,2025-03-26 17:30:00,17
삼척,10.400000,17:30:00,동해,bsc87,2025-03-26 17:30:00,17
영덕,10.600000,17:30:00,동해,byd8a,2025-03-26 17:30:00,17
양양,8.000000,17:30:00,동해,byy87,2025-03-26 17:30:00,17
고성 가진,6.700000,17:30:00,동해,fggo3,2025-03-26 17:30:00,17
구룡포 하정,11.500000,17:30:00,동해,fghe8,2025-03-26 17:30:00,17
기장,11.700000,18:00:00,동해,bgj8a,2025-03-26 18:00:00,18
강릉,9.800000,18:00:00,동해,bgna3,2025-03-26 18:00:00,18
삼척,10.400000,18:00:00,동해,bsc87,2025-03-26 18:00:00,18
영덕,10.500000,18:00:00,동해,byd8a,2025-03-26 18:00:00,18
양양,8.000000,18:00:00,동해,byy87,2025-03-26 18:00:00,18
고성 가진,6.700000,18:00:00,동해,fggo3,2025-03-26 18:00:00,18
구룡포 하정,11.500000,18:00:00,동해,fghe8,2025-03-26 18:00:00,18
기장,11.700000,18:30:00,동해,bgj8a,2025-03-26 18:30:00,18
강릉,9.600000,18:30:00,동해,bgna3,2025-03-26 18:30:00,18
삼척,10.200000,18:30:00,동해,bsc87,2025-03-26 18:30:00,18
영덕,10.500000,18:30:00,동해,byd8a,2025-03-26 18:30:00,18
양양,8.100000,18:30:00,동해,byy87,2025-03-26 18:30:00,18
고성 가진,6.700000,18:30:00,동해,fggo3,2025-03-26 18:30:00,18

In [32]:
df_East
    .groupBy { sta_cde and sta_nam_kor and hour }
    .aggregate {
        min{wtr_tmp} into "min"
        max{wtr_tmp} into "max"
        mean{wtr_tmp} into "mean"
        min{obs_datetime} into "time"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 2600 to 1200
        }

        ribbon {
            x("time") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("sta_nam_kor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(sta_nam_kor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("time")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..12.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(sta_nam_kor)
        }
    }

In [33]:
df_East
    .select{  sta_nam_kor and wtr_tmp and obs_datetime   }
   // .convert{ obs_tim }.with{ LocalTime.parse(it) }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 2600 to 600
        }

        x(obs_datetime) { axis.name = "관측일시"}
        y(wtr_tmp) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(sta_nam_kor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [34]:
val currentTime = df.obs_datetime.max()
currentTime

2025-03-27 16:30:00

In [35]:
import kotlinx.datetime.LocalTime

val df_Current = df.filter {
    obs_datetime.equals(currentTime)   and repair_gbn.equals("1")
  //  gru_nam.equals("동해")
}.select{
    sta_nam_kor and obs_lay and wtr_tmp and gru_nam and    sta_cde  and  lon and lat and obs_datetime
}.convert { wtr_tmp }.with{ it.toFloat()
}.sortBy{sta_nam_kor  and obs_lay }

In [36]:
df_Current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,70,43,0,강릉,3,null,null,강릉,완도 가교,해남 화산
obs_lay,String,70,3,0,1,43,null,null,1,1,3
wtr_tmp,Float,70,37,0,10.000000,5,9.921429,1.804816,5.700000,10.300000,14.600000
gru_nam,String,70,3,0,남해,37,null,null,남해,남해,서해
sta_cde,String,70,43,0,bgna3,3,null,null,bgj8a,fnm5b,wn087
lon,Double,70,43,0,128.949200,3,127.635790,1.180272,124.729500,127.415400,129.549700
lat,Double,70,43,0,37.799000,3,35.518570,1.388290,33.310400,34.806000,38.368100
obs_datetime,String,70,1,0,2025-03-27 16:30:00,70,null,null,2025-03-27 16:30:00,2025-03-27 16:30:00,2025-03-27 16:30:00

In [2]:
val df_current = DataFrame.readJson("http://127.0.0.1:7788/nifs/seawaterinfo/current")
df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,68,43,0,bgj8a,3,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,68,43,0,기장,3,null,null,강릉,완도 감목,해남 화산
obs_datetime,String,68,1,0,2025-03-28 17:00:00,68,null,null,2025-03-28 17:00:00,2025-03-28 17:00:00,2025-03-28 17:00:00
obs_lay,String,68,3,0,1,43,null,null,1,1,3
wtr_tmp,String,68,40,0,9.6,4,null,null,10,11.7,9.9
dox,String?,68,15,53,9.7,2,null,null,10.4,13.2,9.8
sal,String?,68,3,66,34.8,1,null,null,32.3,32.3,34.8
gru_nam,String,68,3,0,남해,37,null,null,남해,남해,서해
lon,Double,68,43,0,129.227000,3,127.571165,1.183756,124.729500,127.074550,129.549700
lat,Double,68,43,0,35.187000,3,35.418725,1.301085,33.310400,34.803000,38.368100

In [159]:
df_current.convert { wtr_tmp }.with{ it.toFloat()}
    .filter { gru_nam.equals("동해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [160]:
df_current.convert { wtr_tmp }.with{ it.toFloat()}
    .filter { gru_nam.equals("남해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [161]:
df_current.convert { wtr_tmp }.with{ it.toFloat()}
    .filter { gru_nam.equals("서해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [6]:
fun<T> makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<T>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        val delimiter1 = if (index < coordinates.size - 1) "," else ""

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        val propertieIterator = properties.entries.iterator()

        while (propertieIterator.hasNext()) {
            val (key, values) = propertieIterator.next()
            val delimiter2 = if (propertieIterator.hasNext()) "," else ""

            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\"${delimiter2} \n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t}${delimiter1}\n"

    }

    return first_str + features_str + end_str
}

In [165]:
val points = df_current.convert { wtr_tmp }.with{ it.toFloat()}.filter {
    obs_lay.equals("1")
}.select{
    sta_cde and sta_nam_kor and  lon and lat
}.sortBy{sta_cde and  sta_nam_kor
}.map { Pair(lon, lat) }.toList()
points.size

43

In [164]:
val properties = df_current.filter {
   obs_lay.equals("1")
}
    .add("tempBoundary"){
        when(wtr_tmp.toFloat()) {
            in 0.0..6.0 -> "Low"
            in 6.1..10.0 -> "Middle"
            in 10.1..16.0 -> "High"
            else -> "Unknown"
        }
    }
    .select {sta_cde and  sta_nam_kor and wtr_tmp and obs_datetime  and "tempBoundary"}
    .sortBy{sta_cde and  sta_nam_kor  }.toMap()

properties["sta_cde"]?.size

43

In [167]:
val pointGeoJSON = makePointGeoJSON(points, properties)

In [168]:
DataFrame.readJsonStr(pointGeoJSON)
    .writeJson("/Volumes/WorkSpace/Notebook/data/nifsPoint.json")

In [169]:
val southKorea = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/southkorea.geojson")
val staPoint = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/nifsPoint.json")

In [170]:
val southKoreaBounds: Envelope = southKorea.bounds().also {
    // Use JTS API for in-place envelope expansion
    it.expandBy(0.2)
}

In [171]:

southKorea.plot{
    layout{
        title = "Korea Sea Water Quality"
      //  size = 1400 to 1400
        //  theme = Theme.HIGH_CONTRAST_DARK
        style(Style.BW) {
            this.panel.background {
                fillColor =  Color.hex("#537ab5")
                borderLineColor = Color.hex("#EFC623")
                borderLineWidth = 6.0
            }
        }
    }

    geoMap{
        fillColor= Color.hex("#e5f5e0")
        borderLine {
            width = 0.5
            color = Color.hex("#a1d99b")
        }
    }

    withData(staPoint) {

        geoPoints {
            size = 5.0
            symbol = Symbol.CIRCLE_FILLED
            fillColor(tempBoundary)
            tooltips(title = value(sta_nam_kor)){
                line("수온 ${value(wtr_tmp)}°C")
                line("측정시간", value(obs_datetime))
            }
        }
    }


}

In [3]:
@file:DependsOn("org.geotools:gt-shapefile:[32.1]")
@file:DependsOn("org.geotools:gt-cql:[32.1]")

In [4]:
import org.geotools.api.data.FileDataStore
import org.geotools.api.data.FileDataStoreFinder
import org.geotools.api.feature.simple.SimpleFeatureType
import java.io.File
import org.geotools.feature.simple.SimpleFeatureTypeBuilder
import org.geotools.referencing.crs.DefaultGeographicCRS
import org.geotools.feature.simple.SimpleFeatureBuilder
import org.geotools.feature.simple.SimpleFeatureImpl
import org.geotools.data.collection.ListFeatureCollection
import org.geotools.geometry.jts.JTSFactoryFinder
import org.locationtech.jts.geom.Point
import org.geotools.data.shapefile.ShapefileDataStoreFactory
import org.geotools.data.simple.SimpleFeatureCollection

In [5]:
var dataStore: FileDataStore = FileDataStoreFinder.getDataStore(File("/Users/unchil/Downloads/south_korea_Boundary.shp"))
val koreaFeatures:SimpleFeatureCollection = dataStore.featureSource.features
val korea = koreaFeatures.toSpatialDataset(10)
dataStore.schema

SimpleFeatureTypeImpl south_korea_Boundary identified extends polygonFeature(the_geom:MultiPolygon)

In [7]:
data class SeawaterInformationByObservationPoint(
    val sta_cde: String,
    val sta_nam_kor: String,
    val obs_datetime: String,
    val obs_lay: String,
    val wtr_tmp: String,
    val dox: String?,
    val sal: String?,
    val gru_nam: String,
    val lon: Double,
    val lat: Double,
)

In [9]:
val dfCurrentList = df_current.filter {
    obs_lay.equals("1")
}.toListOf<SeawaterInformationByObservationPoint>()

In [10]:

fun createFeatureType(): SimpleFeatureType {
    val builder = SimpleFeatureTypeBuilder()
    builder.setName( "Location" )

    builder.add("the_geom", org.locationtech.jts.geom.Point::class.java, DefaultGeographicCRS.WGS84) // 경도, 위도
    builder.add("wtr_tmp", String::class.java)
    builder.add("obs_datetime", String::class.java)
    builder.add("sta_nam_kor", String::class.java)
    builder.add("sta_cde", String::class.java)
    builder.add("tempBoundary",String::class.java)

    return builder.buildFeatureType()
}


fun createFeatureCollection(seaWaterInfo: List<SeawaterInformationByObservationPoint>): SimpleFeatureCollection {
    val featureType = createFeatureType()
    val featureBuilder = SimpleFeatureBuilder(featureType)
    val featureCollection = ListFeatureCollection(featureType)
    val geometryFactory = JTSFactoryFinder.getGeometryFactory()

    seaWaterInfo.forEach { info ->

        val point: Point = geometryFactory.createPoint(org.locationtech.jts.geom.Coordinate(info.lon, info.lat))
        featureBuilder.add(point)
        featureBuilder.add(info.wtr_tmp)
        featureBuilder.add(info.obs_datetime)
        featureBuilder.add(info.sta_nam_kor)
        featureBuilder.add(info.sta_cde)
        featureBuilder.add(
            when(info.wtr_tmp.toFloat()) {
                in 0.0..6.0 -> "Low"
                in 6.1..10.0 -> "Middle"
                in 10.1..16.0 -> "High"
                else -> "Unknown"
            })

        val feature = featureBuilder.buildFeature(null)
        featureCollection.add(feature)
    }
    return featureCollection
}

In [11]:
val pointData = createFeatureCollection(dfCurrentList).toSpatialDataset(10)

In [12]:
val southKoreaBounds = koreaFeatures.bounds
southKoreaBounds.expandBy(1.0)
val southKoreaLimits = coordMap(
    xlim = southKoreaBounds.minX to southKoreaBounds.maxX,
    ylim = southKoreaBounds.minY to southKoreaBounds.maxY
)

In [14]:
letsPlot() +
        geomPolygon(map = korea, fill = "white", color = "gray") +
        geomPoint(
            map=pointData ,
            size = 3,
            shape = 1,
            tooltips = layerTooltips()
                .line("수집시간|@obs_datetime")
                .line("관측지점|@sta_nam_kor/@sta_cde")
                .line("온도|@wtr_tmp °C" )
        ){ color="tempBoundary" } +
        labs( title="Korea EastSea 수온 정보", color="수온범위", caption="Nifs") +
        southKoreaLimits +
        ggsize(800, 800)