In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [5]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250223"
val EDATE = "20250223"
val STA_CD = "bngh3"
val numOfRows = "100"
val maxPage = 5

In [6]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [7]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250223&EDATE=20250223&numOfRows=100

In [146]:
val df = load(url, maxPage)
df

In [147]:
val df2 = df.item.concat()

In [148]:
val df3 = df2.parse()

In [149]:
df3.plot{
    x(obsDtm) { axis.name = "관측일시"}
    y(wtrTmp_1) {axis.name ="표층수온"}

    line{
        color(staNamKor){
            scale = continuous(Color.GREEN..Color.RED)
            legend{
                name = "관측소명"
            }
        }
    }

    layout {
        title = "관측지점별 해수 정보"
        size = 1200 to 500
    }
}

In [150]:
df3.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}

staCde,name,code,currentTemp
bdch3,덕천,bdch3,11.300000
fghe8,구룡포 하정,fghe8,10.500000
fggo3,고성 가진,fggo3,5.500000
byyh3,온양,byyh3,10.800000
byy87,양양,byy87,5.700000
byd8a,영덕,byd8a,10.800000
bsc87,삼척,bsc87,9.300000
bngh3,나곡,bngh3,11
bjhh3,진하,bjhh3,12.100000
bgrh3,고리,bgrh3,12.100000
bgna3,강릉,bgna3,7.300000
bgjh3,기장(한수원),bgjh3,12.800000
bgj8a,기장,bgj8a,12.500000

In [151]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE.csv")
staCodeDf

gru,code,name,isavailable,enddate,latitude,longitude
동해,bgj8a,기장,사용,2008-11-04,35.187000,129.227000
동해,byy87,양양,사용,2008-07-13,38.082700,128.698400
동해,byd8a,영덕,사용,2008-11-04,36.573700,129.437000
동해,bgna3,강릉,사용,2008-07-08,37.799000,128.949200
동해,bsc87,삼척,사용,2008-07-22,37.302300,129.312700
동해,fgbg3,고성 봉포,사용,2016-03-10,38.249400,128.624500
동해,fghe8,구룡포 하정,사용,2014-08-08,35.960700,129.549700
동해,bgjh3,기장(한수원),사용,2017-04-03,35.182500,129.235200
동해,bgrh3,고리,사용,2017-04-03,35.318600,129.314700
동해,bjhh3,진하,사용,2017-04-03,35.384700,129.368000
동해,bjjh3,정자,사용,2017-04-03,35.634700,129.495000
동해,bysh3,월성,사용,2017-04-03,35.717700,129.495000
동해,byph3,양포,사용,2017-04-03,35.865800,129.547200
동해,byyh3,온양,사용,2017-04-03,37.019400,129.425000
동해,bdch3,덕천,사용,2017-04-03,37.100000,129.404100
동해,bngh3,나곡,사용,2017-04-03,37.119100,129.395800
서해,br001,보령 효자도,사용,2005-10-05,36.415800,126.433300
서해,sj086,서산 지곡,사용,2008-06-21,36.893500,126.352400
서해,fbn69,백령도,사용,2006-09-12,37.950500,124.729500
서해,emp67,목포,사용,2006-07-03,34.789200,126.365300

In [152]:
val df_currentMap = df3.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}.join(staCodeDf.select{ name and code and latitude and longitude}){
    "name" and "code"
}.remove { staCde }

df_currentMap

name,code,currentTemp,latitude,longitude
덕천,bdch3,11.300000,37.100000,129.404100
구룡포 하정,fghe8,10.500000,35.960700,129.549700
온양,byyh3,10.800000,37.019400,129.425000
양양,byy87,5.700000,38.082700,128.698400
영덕,byd8a,10.800000,36.573700,129.437000
삼척,bsc87,9.300000,37.302300,129.312700
나곡,bngh3,11,37.119100,129.395800
진하,bjhh3,12.100000,35.384700,129.368000
고리,bgrh3,12.100000,35.318600,129.314700
강릉,bgna3,7.300000,37.799000,128.949200
기장(한수원),bgjh3,12.800000,35.182500,129.235200
기장,bgj8a,12.500000,35.187000,129.227000

In [126]:
df_currentMap.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
name,String,12,12,0,덕천,1,null,null,강릉,나곡,진하
code,String,12,12,0,bdch3,1,null,null,bdch3,bjhh3,fghe8
currentTemp,Number,12,11,0,12.400000,2,10.558333,2.144531,5.700000,10.950000,12.800000
latitude,Double,12,12,0,37.100000,1,36.502475,1.055060,35.182500,36.796550,38.082700
longitude,Double,12,12,0,129.404100,1,129.276400,0.235408,128.698400,129.341350,129.549700

In [334]:
val mapData = df_currentMap.toMap()
mapData

{name=[덕천, 구룡포 하정, 온양, 양양, 영덕, 삼척, 나곡, 진하, 고리, 강릉, 기장(한수원), 기장], code=[bdch3, fghe8, byyh3, byy87, byd8a, bsc87, bngh3, bjhh3, bgrh3, bgna3, bgjh3, bgj8a], currentTemp=[11.3, 10.5, 10.8, 5.7, 10.8, 9.3, 11, 12.1, 12.1, 7.3, 12.8, 12.5], latitude=[37.1, 35.9607, 37.0194, 38.0827, 36.5737, 37.3023, 37.1191, 35.3847, 35.3186, 37.799, 35.1825, 35.187], longitude=[129.4041, 129.5497, 129.425, 128.6984, 129.437, 129.3127, 129.3958, 129.368, 129.3147, 128.9492, 129.2352, 129.227]}

In [24]:
%useLatestDescriptors
%use lets-plot
%use lets-plot-gt

In [263]:
File("/Users/unchil/Downloads/kr.json").readText()

{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                128.3649194916586,
                38.62433506846602
              ],
              [
                128.39478352233803,
                38.57807403654449
              ],
              [
                128.44141679776882,
                38.5058046474157
              ],
              [
                128.45069412484042,
                38.47410702830373
              ],
              [
                128.47445729143752,
                38.42609294764679
              ],
              [
                128.56275479507096,
                38.28896725836469
              ],
              [
                128.6316023609173,
                38.144964828794535
              ],
              [
                128.64283289217417,
                38.12929924307871
              ],
              [
                128.67872159215725,
                38.094305801746344
              ],
              [
                128.69247485661992,
                38.06492756105436
              ],
              [
                128.85914147168063,
                37.87677643345943
              ],
              [
                128.92383867805157,
                37.80231344223282
              ],
              [
                129.00131262777305,
                37.73436095389036
              ],
              [
                129.01229905732353,
                37.72724035872396
              ],
              [
                129.06421951073943,
                37.678859620901854
              ],
              [
                129.06690518163234,
                37.65843339923155
              ],
              [
                129.0671492480604,
                37.63385644888072
              ],
              [
                129.07333421213164,
                37.61302323224269
              ],
              [
                129.10873453648063,
                37.59739811993791
              ],
              [
                129.11898846776958,
                37.58063384019625
              ],
              [
                129.1482039364643,
                37.50511296196439
              ],
              [
                129.16122478872825,
                37.487616248313856
              ],
              [
                129.17684979942868,
                37.48016997770299
              ],
              [
                129.18995198934724,
                37.469387060003534
              ],
              [
                129.2354435897072,
                37.39826086713359
              ],
              [
                129.26278727184055,
                37.37091700002685
              ],
              [
                129.27222745330388,
                37.35586179580484
              ],
              [
                129.27588948053494,
                37.33991113350844
              ],
              [
                129.28280683991042,
                37.32444896503412
              ],
              [
                129.3310653374432,
                37.28217200686375
              ],
              [
                129.34644615336597,
                37.24750396149136
              ],
              [
                129.36011803783376,
                37.17177969493196
              ],
              [
                129.3789168242342,
                37.13011295541665
              ],
              [
                129.43018636590847,
                37.07306544792239
              ],
              [
                129.43409268197954,
                37.06110267238538
              ],
              [
                129.42823328639503,
                37.049546647421934
              ],
              [
                129.41895594833514,
                37.03851963883324
              ],
              [
                129.4130965445425,
                37.02773671144513
              ],
              [
                129.4126896330036,
                37.0180524479819
              ],
              [
                129.41993249535528,
                36.98676179889971
              ],
              [
                129.42872152643235,
                36.89740627550809
              ],
              [
                129.43799892310182,
                36.8561466033231
              ],
              [
                129.47120199840273,
                36.77187730955174
              ],
              [
                129.47388757371843,
                36.73061759368236
              ],
              [
                129.46347089499164,
                36.69245025488219
              ],
              [
                129.44092858013477,
                36.65778229068232
              ],
              [
                129.42261805372473,
                36.61664463136889
              ],
              [
                129.42286218049097,
                36.61497631378594
              ],
              [
                129.4279891042893,
                36.57566961988846
              ],
              [
                129.441660995404,
                36.534654023629834
              ],
              [
                129.4471134879921,
                36.49331291268833
              ],
              [
                129.44092854977077,
                36.40794499606142
              ],
              [
                129.43482507607996,
                36.38959383513561
              ],
              [
                129.403900617629,
                36.35944250519028
              ],
              [
                129.39185633037263,
                36.34247470291887
              ],
              [
                129.38656662026344,
                36.322699318964155
              ],
              [
                129.38233484852174,
                36.20184970697251
              ],
              [
                129.38575280315416,
                36.18545157072572
              ],
              [
                129.391856333332,
                36.176337012473695
              ],
              [
                129.39852949068063,
                36.17267486778776
              ],
              [
                129.4039005976022,
                36.16762931825798
              ],
              [
                129.40967857940143,
                36.1336123672734
              ],
              [
                129.41708416847155,
                36.10757068218868
              ],
              [
                129.4251408288847,
                36.10301342835814
              ],
              [
                129.43051190060388,
                36.09739815277973
              ],
              [
                129.42676841046554,
                36.08177315250974
              ],
              [
                129.41871180061653,
                36.07298414547446
              ],
              [
                129.40829511704283,
                36.068915104254216
              ],
              [
                129.39844810313622,
                36.06631092200706
              ],
              [
                129.38178266731117,
                36.05517462074274
              ],
              [
                129.38085873419672,
                36.04148687540565
              ],
              [
                129.40193704291997,
                36.02566008385368
              ],
              [
                129.41708063588928,
                36.01191271321709
              ],
              [
                129.43305147952037,
                35.996107740267334
              ],
              [
                129.45333141026003,
                35.993287368475535
              ],
              [
                129.479014522199,
                36.00958893984541
              ],
              [
                129.54257244717215,
                36.06590401198159
              ],
              [
                129.5547949501879,
                36.08247790077644
              ],
              [
                129.57129968188633,
                36.071844806541854
              ],
              [
                129.57496180402555,
                36.05467360467459
              ],
              [
                129.58204187466464,
                36.036810635273504
              ],
              [
                129.58725019706847,
                36.01691315495017
              ],
              [
                129.57164376920724,
                35.997124393608935
              ],
              [
                129.53558957050367,
                35.93903566406274
              ],
              [
                129.5328390559502,
                35.91301291274237
              ],
              [
                129.52213432817155,
                35.84455224641817
              ],
              [
                129.4962165011799,
                35.78507393901937
              ],
              [
                129.4976505669609,
                35.747870146995375
              ],
              [
                129.4711259105639,
                35.68322232682156
              ],
              [
                129.4515757091841,
                35.65180229261344
              ],
              [
                129.4430533810115,
                35.636089990608355
              ],
              [
                129.45137576282917,
                35.61824332639677
              ],
              [
                129.4605899019355,
                35.609294211735225
              ],
              [
                129.46727513299754,
                35.59966755413069
              ],
              [
                129.46348789807823,
                35.57788335356626
              ],
              [
                129.46135128896756,
                35.55206139424804
              ],
              [
                129.45460044824299,
                35.51325102767083
              ],
              [
                129.4444279309193,
                35.49681224184934
              ],
              [
                129.42798912508528,
                35.478745827688876
              ],
              [
                129.41285240249607,
                35.4720726439802
              ],
              [
                129.40626062011023,
                35.48969148627558
              ],
              [
                129.40040123935864,
                35.512640694534454
              ],
              [
                129.38746179164653,
                35.52985261839194
              ],
              [
                129.37354576042674,
                35.53278227801583
              ],
              [
                129.365244979249,
                35.51325102767083
              ],
              [
                129.37891686869315,
                35.51068757762312
              ],
              [
                129.38705489307063,
                35.50226473293012
              ],
              [
                129.39096113081206,
                35.48993560804714
              ],
              [
                129.39185631615112,
                35.475734768282365
              ],
              [
                129.3874617805897,
                35.4623070247553
              ],
              [
                129.37720787368718,
                35.45917388506617
              ],
              [
                129.3657332785976,
                35.45831942094763
              ],
              [
                129.35775800319456,
                35.45180897514023
              ],
              [
                129.35922285701997,
                35.44464753739312
              ],
              [
                129.36050348235798,
                35.42605607141531
              ],
              [
                129.36458132178467,
                35.40687004347947
              ],
              [
                129.35526190835103,
                35.394571769408714
              ],
              [
                129.34678727395155,
                35.382272545412825
              ],
              [
                129.35512974114692,
                35.37266730426348
              ],
              [
                129.36181399472392,
                35.36717183986583
              ],
              [
                129.36044354895196,
                35.35358306176485
              ],
              [
                129.33987503686387,
                35.348074246772704
              ],
              [
                129.32051320711886,
                35.338545466584755
              ],
              [
                129.29271987070393,
                35.31604909220609
              ],
              [
                129.26920554365435,
                35.316766521703805
              ],
              [
                129.2641262943158,
                35.30242762024375
              ],
              [
                129.26240016579644,
                35.28398875403829
              ],
              [
                129.25648417429062,
                35.274421526318335
              ],
              [
                129.2497345730216,
                35.266227744154875
              ],
              [
                129.25538170560753,
                35.25259023337263
              ],
              [
                129.25570722934023,
                35.246975006416505
              ],
              [
                129.24439034103938,
                35.228218034408044
              ],
              [
                129.22847902657912,
                35.20053055220414
              ],
              [
                129.2106926093402,
                35.18300137632158
              ],
              [
                129.20108409470524,
                35.16662808733563
              ],
              [
                129.19434655231038,
                35.15550365237764
              ],
              [
                129.17889555491095,
                35.15575745562129
              ],
              [
                129.1674798471191,
                35.15616830722566
              ],
              [
                129.1534123078086,
                35.154282948428204
              ],
              [
                129.14307701808067,
                35.154771224257196
              ],
              [
                129.13220458103447,
                35.1507664440654
              ],
              [
                129.12025714823804,
                35.14961672155504
              ],
              [
                129.11929663568358,
                35.135567199296965
              ],
              [
                129.1272805059156,
                35.12582503004386
              ],
              [
                129.12860118248102,
                35.114147972812276
              ],
              [
                129.1234700822866,
                35.10084547544432
              ],
              [
                129.10107818517463,
                35.09227615333202
              ],
              [
                129.08296636167412,
                35.10518477848059
              ],
              [
                129.0719980522827,
                35.11261736573752
              ],
              [
                129.06384041858058,
                35.12084708930413
              ],
              [
                129.03762722466786,
                35.097834223565776
              ],
              [
                129.02568968283103,
                35.07950225058137
              ],
              [
                129.02186185345346,
                35.0599831059592
              ],
              [
                129.01375367605732,
                35.055307289109116
              ],
              [
                129.00895713177616,
                35.06513447566961
              ],
              [
                128.9970261059192,
                35.07572809674976
              ],
              [
                128.99801473373338,
                35.06628118749215
              ],
              [
                129.00040153085396,
                35.04595001962722
              ],
              [
                128.99276994357413,
                35.04596265818832
              ],
              [
                128.98940546003868,
                35.05269402597902
              ],
              [
                128.98511156052157,
                35.05428378099372
              ],
              [
                128.97486412797494,
                35.048651432046384
              ],
              [
                128.96512461787458,
                35.043648797667345
              ],
              [
                128.95844737979587,
                35.050387048516924
              ],
              [
                128.950360400025,
                35.072913013047575
              ],
              [
                128.9537036060613,
                35.09320167011653
              ],
              [
                128.96134093942342,
                35.118954639705855
              ],
              [
                128.96277764447942,
                35.1333859938106
              ],
              [
                128.95800991628727,
                35.136896887345024
              ],
              [
                128.94894401670274,
                35.125974670435006
              ],
              [
                128.91841959285924,
                35.08188205273191
              ],
              [
                128.90459292689718,
                35.08109865170865
              ],
              [
                128.90363532003337,
                35.10139002316041
              ],
              [
                128.90458592913862,
                35.12050992026366
              ],
              [
                128.89792560857137,
                35.12130533108657
              ],
              [
                128.88925214965585,
                35.10545482124804
              ],
              [
                128.88218607147508,
                35.081484779809685
              ],
              [
                128.8574024258276,
                35.083823078671585
              ],
              [
                128.7915554411254,
                35.082953206333016
              ],
              [
                128.78777325579895,
                35.10131859642664
              ],
              [
                128.78107691666818,
                35.11106214917639
              ],
              [
                128.77198831933762,
                35.08331323964367
              ],
              [
                128.76197088684816,
                35.07939239152398
              ],
              [
                128.73868948737152,
                35.08798761889524
              ],
              [
                128.72779381557095,
                35.10472239718244
              ],
              [
                128.71583092584277,
                35.10586172260584
              ],
              [
                128.70045006725772,
                35.09613678839782
              ],
              [
                128.70045006628303,
                35.139878648538634
              ],
              [
                128.69629967560175,
                35.143500068145016
              ],
              [
                128.68775475390518,
                35.14061106981953
              ],
              [
                128.68051191702781,
                35.13141510986145
              ],
              [
                128.6799422524018,
                35.115952863954895
              ],
              [
                128.66407311221977,

In [139]:
import org.geotools.geojson.feature.FeatureJSON
val southKr = FeatureJSON().readFeatureCollection(File("/Users/unchil/Downloads/kr.json").readText())
val mapBound = southKr.bounds
mapBound.expandBy(0.2)

In [308]:
mapBound

ReferencedEnvelope[124.41361734912914 : 132.0625218795587, 32.99757736099913 : 38.82433506846602]

In [307]:
fun makePointGeoJSON():String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"


    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var middle_str = ""

    df_currentMap.forEach {
        middle_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${it.longitude}, ${it.latitude}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n" +
                "\t\t\t\t\"name\": \"${it.name}\",\n" +
                "\t\t\t\t\"currentTemp\": ${it.currentTemp}\n" +
                "\t\t\t}\n" +
                "\t\t},\n"
    }


    return   first_str + middle_str + end_str
}
val point = FeatureJSON().readFeatureCollection(makePointGeoJSON())
point.bounds

ReferencedEnvelope[128.6984 : 129.5497, 35.1825 : 38.0827]

In [330]:
makePointGeoJSON()

{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.4041, 37.1]
			},
			"properties": {
				"name": "덕천",
				"currentTemp": 11.3
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.5497, 35.9607]
			},
			"properties": {
				"name": "구룡포 하정",
				"currentTemp": 10.5
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.425, 37.0194]
			},
			"properties": {
				"name": "온양",
				"currentTemp": 10.8
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.6984, 38.0827]
			},
			"properties": {
				"name": "양양",
				"currentTemp": 5.7
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.437, 36.5737]
			},
			"properties": {
				"name": "영덕",
				"currentTemp": 10.8
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3127, 37.3023]
			},
			"properties": {
				"name": "삼척",
				"currentTemp": 9.3
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3958, 37.1191]
			},
			"properties": {
				"name": "나곡",
				"currentTemp": 11
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.368, 35.3847]
			},
			"properties": {
				"name": "진하",
				"currentTemp": 12.1
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3147, 35.3186]
			},
			"properties": {
				"name": "고리",
				"currentTemp": 12.1
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.9492, 37.799]
			},
			"properties": {
				"name": "강릉",
				"currentTemp": 7.3
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.2352, 35.1825]
			},
			"properties": {
				"name": "기장(한수원)",
				"currentTemp": 12.8
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.227, 35.187]
			},
			"properties": {
				"name": "기장",
				"currentTemp": 12.5
			}
		},
	]
}

In [358]:
letsPlot() +
        geomMap(map = southKr.toSpatialDataset() , color = "#a1d99b", fill = "gray" ) +
        geomRect(xmin= mapBound.minX, xmax =mapBound.maxX, ymax=mapBound.maxY, ymin= mapBound.minY, alpha = 0, color="orange") +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        geomPoint(map=point.toSpatialDataset() , size=4, color="red" , alpha=0.5) +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = +.2) , color="yellow"){ label =  "currentTemp" } +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = -.2) , color="black"){ label = "name" } +
        theme(panelBackground = elementRect(color = "black", fill = "#537ab5")) +
        ggtitle("Korea EastSeaWater Quality") +
        ggsize( width = 1000, height = 900)