In [35]:
%useLatestDescriptors
%use dataframe
%use kandy
%use ktor-client

In [34]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
val serviceKeyFilePath = "/Volumes/WorkSpace/Notebook/data/OceanMensurationService.json"

In [104]:
val serviceInfo = DataRow.readJson(path=serviceKeyFilePath)

In [125]:
val codeUrl = "${serviceInfo.endpoint_json}?id=${serviceInfo.code}&key=${serviceInfo.key}"

In [132]:
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.utils.io.charsets.*

val codeResponse = http.get(codeUrl){
  //  contentType(ContentType.Application.Json.withCharset(Charset.forName("EUC-KR")) )
}
codeResponse

HttpResponse[https://www.nifs.go.kr/bweb/OpenAPI_json?id=risaCode&key=qPwOeIrU-2502-ZJMYJU-1060, 200 OK]

In [133]:
val codeRawDf = DataFrame.readJsonStr( codeResponse.bodyAsText(Charset.forName("EUC-KR")) )
codeRawDf

In [135]:
val codeDf = codeRawDf.body.item.concat()
codeDf

bld_dat,lon,sta_nam_kor,bot_dep,gru_nam,sur_dep,mid_tmp_yn,sta_cde,sta_des,end_dat,sur_tmp_yn,bot_tmp_yn,lat,mid_dep
2024-05-13,126.7364,완도 대창,null,남해,3,N,fwdo5,null,null,Y,N,34.3825,null
2024-05-13,127.0837,완도 사동,null,남해,3,N,fwso5,null,null,Y,N,34.3373,null
2024-05-09,127.0101,완도 감목,null,남해,5,N,fwyo5,null,null,Y,N,34.342,null
2024-03-11,128.5239,고성 가진,28,동해,5,Y,fggo3,null,null,Y,Y,38.3681,15
2020-05-28,126.147,태안 파도리,null,서해,1.5,Y,ftpk5,태안군청 신규관측소,null,Y,N,36.7123,2.5
2020-05-28,126.4202,태안 대야도,null,서해,6,Y,ftdk5,태안군청 신규관측소,null,Y,N,36.4808,12
2019-07-02,128.5142,거제 가조,10,남해,1,Y,fggj7,빈산소수괴 관측시스템,2019-12-12,Y,Y,34.9772,6
2019-03-28,128.345,통영 수월,null,남해,5,N,ftsj3,null,null,Y,N,34.8222,null
2019-03-27,127.1228,고흥 소록도,null,남해,3,N,fgsj3,null,null,Y,N,34.5049,null
2018-11-22,125.4564,흑산도 대둔,null,서해,2.5,N,fhdib,null,2019-05-17,Y,N,34.73297,null
2018-11-21,126.4067,함평만,null,서해,2.5,N,fhpib,null,2019-05-20,Y,N,35.09017,null
2018-04-03,126.4422,군산 신시도,null,서해,2,N,egsi4,null,null,Y,N,35.8168,null
2017-06-13,126.9941,완도 일정,null,남해,2.5,N,fwih6,완도군 금일읍 일정리,null,Y,N,34.3674,null
2017-06-13,126.3717,서산 창리,null,서해,5,Y,fsch6,충남 서산시 부석면 창리,null,Y,N,36.6163,10
2016-03-29,126.768,완도 망남,null,남해,2,Y,fwmg3,전라남도 완도군 완도군청 설치,null,Y,N,34.3013,6
2016-03-18,128.626,고성 봉포,30,동해,5,Y,fgbg3,2020년 7월 4일부로 고성 봉포지역에서 속초 장사항으로 이전설치...,2024-02-15,Y,Y,38.2267,20
2015-12-11,126.2248,신안 압해,null,서해,7,N,esafc,전라남도 신안군 전라남도 해양수산과학원 설치,null,Y,N,34.8483,null
2015-12-11,126.2189,진도 전두,null,서해,3,Y,fjdfc,전라남도 진도군 전라남도 해양수산과학원 설치,null,Y,N,34.5376,7
2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
2015-12-11,126.4216,해남 화산,null,남해,1,Y,fhhfc,전라남도 해남군 전라남도 해양수산과학원 설치,null,Y,N,34.4235,3

In [130]:
val listUrl = "${serviceInfo.endpoint_json}?id=${serviceInfo.list}&key=${serviceInfo.key}"
val listRawDf = DataFrame.readJsonStr( http.get(listUrl).bodyAsText(Charset.forName("EUC-KR")) )
listRawDf

In [131]:
val listDf = listRawDf.body.item.concat()
listDf

sta_nam_kor,wtr_tmp,obs_lay,repair_gbn,obs_tim,dox,sta_cde,sal,obs_dat
기장,11.8,1,1,14:30:00,null,bgj8a,null,2025-02-26
기장,11.9,2,1,14:30:00,null,bgj8a,null,2025-02-26
기장,11.9,3,1,14:30:00,null,bgj8a,null,2025-02-26
강릉,7.3,1,1,14:30:00,null,bgna3,null,2025-02-26
강릉,7.1,2,1,14:30:00,null,bgna3,null,2025-02-26
강릉,6.3,3,1,14:30:00,null,bgna3,null,2025-02-26
태안 고남,3.9,1,1,14:30:00,null,br001,null,2025-02-26
삼척,9.6,1,1,14:30:00,null,bsc87,null,2025-02-26
삼척,9.1,2,1,14:30:00,null,bsc87,null,2025-02-26
삼척,9,3,1,14:30:00,null,bsc87,null,2025-02-26
영덕,10.2,1,1,14:30:00,null,byd8a,null,2025-02-26
영덕,10,2,1,14:30:00,null,byd8a,null,2025-02-26
영덕,10,3,1,14:30:00,null,byd8a,null,2025-02-26
양양,5.5,1,1,14:30:00,null,byy87,null,2025-02-26
양양,5.4,2,1,14:30:00,null,byy87,null,2025-02-26
양양,5.3,3,1,14:30:00,null,byy87,null,2025-02-26
군산 신시도,3.8,1,1,14:30:00,null,egsi4,null,2025-02-26
장흥 회진,7.1,1,1,14:30:00,12.8,ejhfc,null,2025-02-26
장흥 회진,7.1,2,1,14:30:00,null,ejhfc,null,2025-02-26
서제주,13.2,1,1,14:30:00,null,ejj47,34.9,2025-02-26

In [137]:
val df = listDf.innerJoinWith(codeDf) {
    right.sta_cde == sta_cde
}
df

sta_nam_kor,wtr_tmp,obs_lay,repair_gbn,obs_tim,dox,sta_cde,sal,obs_dat,bld_dat,lon,sta_nam_kor1,bot_dep,gru_nam,sur_dep,mid_tmp_yn,sta_cde1,sta_des,end_dat,sur_tmp_yn,bot_tmp_yn,lat,mid_dep
기장,11.8,1,1,14:30:00,null,bgj8a,null,2025-02-26,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
기장,11.9,2,1,14:30:00,null,bgj8a,null,2025-02-26,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
기장,11.9,3,1,14:30:00,null,bgj8a,null,2025-02-26,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
강릉,7.3,1,1,14:30:00,null,bgna3,null,2025-02-26,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
강릉,7.1,2,1,14:30:00,null,bgna3,null,2025-02-26,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
강릉,6.3,3,1,14:30:00,null,bgna3,null,2025-02-26,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
태안 고남,3.9,1,1,14:30:00,null,br001,null,2025-02-26,2005-10-05,126.4333,태안 고남,null,서해,3,N,br001,관측소 위치에 맞는 이름현행화를 위하여 [보령 효자도]를 [태안 고...,null,Y,N,36.4158,null
삼척,9.6,1,1,14:30:00,null,bsc87,null,2025-02-26,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
삼척,9.1,2,1,14:30:00,null,bsc87,null,2025-02-26,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
삼척,9,3,1,14:30:00,null,bsc87,null,2025-02-26,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
영덕,10.2,1,1,14:30:00,null,byd8a,null,2025-02-26,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
영덕,10,2,1,14:30:00,null,byd8a,null,2025-02-26,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
영덕,10,3,1,14:30:00,null,byd8a,null,2025-02-26,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
양양,5.5,1,1,14:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
양양,5.4,2,1,14:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
양양,5.3,3,1,14:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
군산 신시도,3.8,1,1,14:30:00,null,egsi4,null,2025-02-26,2018-04-03,126.4422,군산 신시도,null,서해,2,N,egsi4,null,null,Y,N,35.8168,null
장흥 회진,7.1,1,1,14:30:00,12.8,ejhfc,null,2025-02-26,2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
장흥 회진,7.1,2,1,14:30:00,null,ejhfc,null,2025-02-26,2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
서제주,13.2,1,1,14:30:00,null,ejj47,34.9,2025-02-26,2004-07-30,126.164,서제주,null,남해,2,N,ejj47,제주시 북제주군 한경면 고산리 차귀도잠수함,null,Y,N,33.3104,null

In [183]:
df.filter { gru_nam.equals("동해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }
        }
    }

In [178]:
df.filter { gru_nam.equals("서해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }
        }
    }

In [181]:
df.filter { gru_nam.equals("남해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }
        }
    }