In [17]:
%useLatestDescriptors
%use dataframe
%use kandy

In [193]:
USE{
    dependencies("org.json:json:20250107")
}

In [194]:
import org.json.XML

In [195]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [328]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250220"
val EDATE = "20250220"
val STA_CD = "bngh3"
val numOfRows = "100"
val maxPage = 5

In [330]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            var instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [331]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250220&EDATE=20250220&numOfRows=100

In [332]:
val df = load(url, maxPage)
df

Can not get nested column 'item' from ValueColumn 'items'

In [335]:
val df2 = df.item.concat()

In [336]:
df2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,301,13,0,강릉,27,null,null,강릉,나곡,진하
cdt_1,Double?,301,83,172,35.130000,5,34.480178,0.296495,34.264000,34.362000,35.136000
obsDtm,String,301,25,0,2025-02-20 12:00:00,13,null,null,2025-02-20 00:00:00,2025-02-20 06:00:00,2025-02-20 12:00:00
staCde,String,301,13,0,bgna3,27,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,301,25,0,120000,13,null,null,null,null,null
wtrTmp_1,Number,301,32,0,5.800000,32,10.073422,2.316598,5.700000,11.100000,12.500000
gruNam,String,301,1,0,동해,301,null,null,동해,동해,동해
wtrTmp_3,Number?,301,32,153,5.700000,17,8.261486,2.513515,5.200000,7.800000,12.100000
wtrTmp_2,Number?,301,24,153,5.700000,28,8.453378,2.422946,5.500000,8.200000,12.200000

In [ ]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE.csv")
staCodeDf