In [29]:
%useLatestDescriptors
%use dataframe
%use kandy
%use ktor-client
%use kandy-geo

In [2]:
val serviceInfo = DataRow.readJson(path="/Volumes/WorkSpace/Notebook/data/OceanMensurationService.json")

In [16]:
val codeUrl = "${serviceInfo.endpoint_json}?id=${serviceInfo.code}&key=${serviceInfo.key}"
val codeRawDf = DataFrame.readJsonStr(  http.get(codeUrl).bodyAsText(java.nio.charset.Charset.forName("EUC-KR")) )
codeRawDf

In [45]:
val codeDf = codeRawDf.body.item.concat()
codeDf

bld_dat,lon,sta_nam_kor,bot_dep,gru_nam,sur_dep,mid_tmp_yn,sta_cde,sta_des,end_dat,sur_tmp_yn,bot_tmp_yn,lat,mid_dep
2024-05-13,126.7364,완도 대창,null,남해,3,N,fwdo5,null,null,Y,N,34.3825,null
2024-05-13,127.0837,완도 사동,null,남해,3,N,fwso5,null,null,Y,N,34.3373,null
2024-05-09,127.0101,완도 감목,null,남해,5,N,fwyo5,null,null,Y,N,34.342,null
2024-03-11,128.5239,고성 가진,28,동해,5,Y,fggo3,null,null,Y,Y,38.3681,15
2020-05-28,126.147,태안 파도리,null,서해,1.5,Y,ftpk5,태안군청 신규관측소,null,Y,N,36.7123,2.5
2020-05-28,126.4202,태안 대야도,null,서해,6,Y,ftdk5,태안군청 신규관측소,null,Y,N,36.4808,12
2019-07-02,128.5142,거제 가조,10,남해,1,Y,fggj7,빈산소수괴 관측시스템,2019-12-12,Y,Y,34.9772,6
2019-03-28,128.345,통영 수월,null,남해,5,N,ftsj3,null,null,Y,N,34.8222,null
2019-03-27,127.1228,고흥 소록도,null,남해,3,N,fgsj3,null,null,Y,N,34.5049,null
2018-11-22,125.4564,흑산도 대둔,null,서해,2.5,N,fhdib,null,2019-05-17,Y,N,34.73297,null
2018-11-21,126.4067,함평만,null,서해,2.5,N,fhpib,null,2019-05-20,Y,N,35.09017,null
2018-04-03,126.4422,군산 신시도,null,서해,2,N,egsi4,null,null,Y,N,35.8168,null
2017-06-13,126.9941,완도 일정,null,남해,2.5,N,fwih6,완도군 금일읍 일정리,null,Y,N,34.3674,null
2017-06-13,126.3717,서산 창리,null,서해,5,Y,fsch6,충남 서산시 부석면 창리,null,Y,N,36.6163,10
2016-03-29,126.768,완도 망남,null,남해,2,Y,fwmg3,전라남도 완도군 완도군청 설치,null,Y,N,34.3013,6
2016-03-18,128.626,고성 봉포,30,동해,5,Y,fgbg3,2020년 7월 4일부로 고성 봉포지역에서 속초 장사항으로 이전설치...,2024-02-15,Y,Y,38.2267,20
2015-12-11,126.2248,신안 압해,null,서해,7,N,esafc,전라남도 신안군 전라남도 해양수산과학원 설치,null,Y,N,34.8483,null
2015-12-11,126.2189,진도 전두,null,서해,3,Y,fjdfc,전라남도 진도군 전라남도 해양수산과학원 설치,null,Y,N,34.5376,7
2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
2015-12-11,126.4216,해남 화산,null,남해,1,Y,fhhfc,전라남도 해남군 전라남도 해양수산과학원 설치,null,Y,N,34.4235,3

In [46]:
val listUrl = "${serviceInfo.endpoint_json}?id=${serviceInfo.list}&key=${serviceInfo.key}"
val listRawDf = DataFrame.readJsonStr( http.get(listUrl).bodyAsText(java.nio.charset.Charset.forName("EUC-KR")) )
listRawDf

In [47]:
val listDf = listRawDf.body.item.concat()
listDf

sta_nam_kor,wtr_tmp,obs_lay,repair_gbn,obs_tim,dox,sta_cde,sal,obs_dat
기장,11.8,1,1,18:30:00,null,bgj8a,null,2025-02-27
기장,11.8,2,1,18:30:00,null,bgj8a,null,2025-02-27
기장,11.8,3,1,18:30:00,null,bgj8a,null,2025-02-27
강릉,7.4,1,1,18:30:00,null,bgna3,null,2025-02-27
강릉,6.4,2,1,18:30:00,null,bgna3,null,2025-02-27
강릉,6.1,3,1,18:30:00,null,bgna3,null,2025-02-27
태안 고남,4.2,1,1,18:30:00,null,br001,null,2025-02-27
삼척,9.7,1,1,18:30:00,null,bsc87,null,2025-02-27
삼척,9.5,2,1,18:30:00,null,bsc87,null,2025-02-27
삼척,8.3,3,1,18:30:00,null,bsc87,null,2025-02-27
영덕,10.4,1,1,18:30:00,null,byd8a,null,2025-02-27
영덕,10.2,2,1,18:30:00,null,byd8a,null,2025-02-27
영덕,10,3,1,18:30:00,null,byd8a,null,2025-02-27
양양,5.4,1,1,20:30:00,null,byy87,null,2025-02-26
양양,5.4,2,1,20:30:00,null,byy87,null,2025-02-26
양양,5.4,3,1,20:30:00,null,byy87,null,2025-02-26
군산 신시도,4.1,1,1,18:30:00,null,egsi4,null,2025-02-27
장흥 회진,7.4,1,1,18:30:00,12.1,ejhfc,null,2025-02-27
장흥 회진,7.3,2,1,18:30:00,null,ejhfc,null,2025-02-27
서제주,13.1,1,1,18:30:00,null,ejj47,34.8,2025-02-27

In [50]:
val df = listDf.innerJoinWith(codeDf) {
    right.sta_cde == sta_cde
}
df

sta_nam_kor,wtr_tmp,obs_lay,repair_gbn,obs_tim,dox,sta_cde,sal,obs_dat,bld_dat,lon,sta_nam_kor1,bot_dep,gru_nam,sur_dep,mid_tmp_yn,sta_cde1,sta_des,end_dat,sur_tmp_yn,bot_tmp_yn,lat,mid_dep
기장,11.8,1,1,18:30:00,null,bgj8a,null,2025-02-27,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
기장,11.8,2,1,18:30:00,null,bgj8a,null,2025-02-27,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
기장,11.8,3,1,18:30:00,null,bgj8a,null,2025-02-27,2008-11-04,129.227,기장,15,동해,5,Y,bgj8a,null,null,Y,Y,35.187,10
강릉,7.4,1,1,18:30:00,null,bgna3,null,2025-02-27,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
강릉,6.4,2,1,18:30:00,null,bgna3,null,2025-02-27,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
강릉,6.1,3,1,18:30:00,null,bgna3,null,2025-02-27,2008-07-08,128.9492,강릉,30,동해,5,Y,bgna3,강원도 강릉시 사천면 사천항,null,Y,Y,37.799,20
태안 고남,4.2,1,1,18:30:00,null,br001,null,2025-02-27,2005-10-05,126.4333,태안 고남,null,서해,3,N,br001,관측소 위치에 맞는 이름현행화를 위하여 [보령 효자도]를 [태안 고...,null,Y,N,36.4158,null
삼척,9.7,1,1,18:30:00,null,bsc87,null,2025-02-27,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
삼척,9.5,2,1,18:30:00,null,bsc87,null,2025-02-27,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
삼척,8.3,3,1,18:30:00,null,bsc87,null,2025-02-27,2008-07-22,129.3127,삼척,25,동해,5,Y,bsc87,강원도 삼척시 근덕면 장호항,null,Y,Y,37.3023,15
영덕,10.4,1,1,18:30:00,null,byd8a,null,2025-02-27,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
영덕,10.2,2,1,18:30:00,null,byd8a,null,2025-02-27,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
영덕,10,3,1,18:30:00,null,byd8a,null,2025-02-27,2008-11-04,129.437,영덕,30,동해,5,Y,byd8a,null,null,Y,Y,36.5737,20
양양,5.4,1,1,20:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
양양,5.4,2,1,20:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
양양,5.4,3,1,20:30:00,null,byy87,null,2025-02-26,2008-07-13,128.6998,양양,25,동해,5,Y,byy87,강원도 양양군 수산항,null,Y,Y,38.0808,15
군산 신시도,4.1,1,1,18:30:00,null,egsi4,null,2025-02-27,2018-04-03,126.4422,군산 신시도,null,서해,2,N,egsi4,null,null,Y,N,35.8168,null
장흥 회진,7.4,1,1,18:30:00,12.1,ejhfc,null,2025-02-27,2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
장흥 회진,7.3,2,1,18:30:00,null,ejhfc,null,2025-02-27,2015-12-11,126.9809,장흥 회진,null,남해,2,Y,ejhfc,전라남도 장흥군 전라남도 해양수산과학원 설치,null,Y,N,34.4699,5
서제주,13.1,1,1,18:30:00,null,ejj47,34.8,2025-02-27,2004-07-30,126.164,서제주,null,남해,2,N,ejj47,제주시 북제주군 한경면 고산리 차귀도잠수함,null,Y,N,33.3104,null

In [66]:
df.filter { gru_nam.equals("동해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [67]:
df.filter { gru_nam.equals("서해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }
        }
    }

In [68]:
df.filter { gru_nam.equals("남해") && repair_gbn.equals("1") }
    .select { sta_nam_kor and obs_lay and wtr_tmp }
    .convert{ wtr_tmp }.with { it.toFloat() }
    .sortBy { sta_nam_kor and obs_lay  }
    .groupBy("obs_lay")
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }
        }
    }

In [25]:
fun<T> makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<T>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        val delimiter1 = if (index < coordinates.size - 1) "," else ""

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        val propertieIterator = properties.entries.iterator()

        while (propertieIterator.hasNext()) {
            val (key, values) = propertieIterator.next()
            val delimiter2 = if (propertieIterator.hasNext()) "," else ""

            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\"${delimiter2} \n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t}${delimiter1}\n"

    }

    return first_str + features_str + end_str
}

In [26]:
val coordinates = df.filter { obs_lay.equals("1") && repair_gbn.equals("1") }
    .select { lon and lat  }
    .convert{ lon and lat }.with { it.toDouble() }


val properties = df.filter { obs_lay.equals("1") && repair_gbn.equals("1") }
    .add("tempBoundary"){
        when(wtr_tmp.toDouble()) {
            in 0.0..4.9 -> "Low"
            in 5.0..7.9 -> "Middle"
            in 8.0..15.9 -> "High"
            else -> "Unknown"
        }
    }
    .select { sta_nam_kor and wtr_tmp and obs_tim  and "tempBoundary"}
// .convert{ wtr_tmp }.with { it.toDouble() }

In [27]:
DataFrame.readJsonStr(makePointGeoJSON(coordinates.map { Pair(lon, lat) }.toList(), properties.toMap()))
    .writeJson("/Volumes/WorkSpace/Notebook/data/point.json")

In [40]:
val southKorea = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/southkorea.geojson")
val staPoint = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/point.json")

In [159]:
val southKoreaBounds: Envelope = southKorea.bounds().also {
    // Use JTS API for in-place envelope expansion
    it.expandBy(0.2)
}

In [185]:

southKorea.plot{
    layout{
        title = "Korea Sea Water Quality"
        size = 1400 to 1400
        theme = Theme.HIGH_CONTRAST_DARK
        style {
            this.panel.background {
                fillColor =  Color.hex("#537ab5")
            }
        }
    }

    geoMap{
        fillColor= Color.hex("#e5f5e0")
        borderLine {
            width = 0.5
            color = Color.hex("#a1d99b")
        }
    }

    withData(staPoint) {
        geoPoints {
            size = 5.0
            symbol = Symbol.CIRCLE_FILLED

            tooltips(title = value(sta_nam_kor)){
                line("수온 ${value(wtr_tmp)}°C")
                line("측정시간", value(obs_tim))
            }
            fillColor(tempBoundary)
        }
    }

}

In [33]:
%useLatestDescriptors
%use lets-plot
%use lets-plot-gt

In [42]:
import org.geotools.geojson.feature.FeatureJSON
val southKr = FeatureJSON().readFeatureCollection(File("/Volumes/WorkSpace/Notebook/data/southkorea.geojson").readText())
val mapBound = southKr.bounds
mapBound.expandBy(0.2)

In [43]:
val point = FeatureJSON().readFeatureCollection(
    makePointGeoJSON( coordinates.map{Pair(lon, lat)}.toList(), properties.toMap())
)

In [78]:
letsPlot() +
        geomMap(map = southKr.toSpatialDataset() , color = "#a1d99b", fill = "#e5f5e0" ) +
        geomRect(xmin= mapBound.minX, xmax =mapBound.maxX, ymax=mapBound.maxY, ymin= mapBound.minY, alpha = 0, fill = "black", color="#EFC623", size=6) +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        geomPoint(
            map= point.toSpatialDataset() ,
            showLegend=true,
            size=3,
            shape = 21,
            fillBy = "paint_a",
            tooltips = layerTooltips().title("@sta_nam_kor").line("수온:@wtr_tmp°C\n@obs_tim")
        ){
            paint_a = "tempBoundary"
        } +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = +.2) , color="yellow"){ label =  "wtr_tmp"} +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = -.2) , color="black"){ label = "sta_nam_kor" } +
        theme(panelBackground = elementRect(color = "black", fill = "#537ab5")) +
        ggtitle("Korea Sea Water Quality") +
        ggsize( width = 1400, height = 1400)