In [17]:
%useLatestDescriptors
%use dataframe
%use kandy

In [193]:
USE{
    dependencies("org.json:json:20250107")
}

In [194]:
import org.json.XML

In [195]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [328]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250220"
val EDATE = "20250220"
val STA_CD = "bngh3"
val numOfRows = "100"
val maxPage = 5

In [338]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [339]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250220&EDATE=20250220&numOfRows=100

In [343]:
val df = load(url, maxPage)
df

Can not get nested column 'item' from ValueColumn 'items'

In [344]:
val df2 = df.item.concat()

In [342]:
df2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,314,13,0,기장,29,null,null,강릉,나곡,진하
cdt_1,Double?,314,85,178,34.439000,6,34.484471,0.299265,34.264000,34.360500,35.136000
obsDtm,String,314,26,0,2025-02-20 12:30:00,13,null,null,2025-02-20 00:00:00,2025-02-20 06:00:00,2025-02-20 12:30:00
staCde,String,314,13,0,bgj8a,29,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,314,26,0,123000,13,null,null,null,null,null
wtrTmp_1,Number,314,33,0,5.800000,32,10.107962,2.311321,5.700000,11.200000,12.500000
gruNam,String,314,1,0,동해,314,null,null,동해,동해,동해
wtrTmp_3,Number?,314,32,159,5.700000,18,8.313548,2.541118,5.200000,8.900000,12.100000
wtrTmp_2,Number?,314,25,159,5.700000,28,8.511613,2.443463,5.500000,9.200000,12.200000

In [347]:
val df3 = df2.parse()

In [348]:
df3.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,372,13,0,기장,32,null,null,강릉,나곡,진하
obsDtm,kotlinx.datetime.LocalDateTime,372,31,0,2025-02-20T14:30,13,null,null,2025-02-20T00:00,2025-02-20T07:30,2025-02-20T15:00
staCde,String,372,13,0,bgj8a,32,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,372,31,0,143000,13,null,null,null,null,null
wtrTmp_3,Number?,372,36,184,5.700000,24,8.260638,2.534266,5.200000,8.850000,12.100000
wtrTmp_1,Number,372,40,0,5.800000,39,10.061290,2.342254,5.700000,11.100000,13.100000
gruNam,String,372,1,0,동해,372,null,null,동해,동해,동해
wtrTmp_2,Number?,372,27,184,5.700000,32,8.462234,2.434733,5.500000,9.200000,12.200000
cdt_1,Double?,372,95,217,34.439000,5,34.477568,0.295999,34.264000,34.352000,35.160000

In [349]:
df3

staNamKor,obsDtm,staCde,obsTim,wtrTmp_3,wtrTmp_1,gruNam,wtrTmp_2,cdt_1
기장,2025-02-20T15:00,bgj8a,150000,12,12.300000,동해,12.200000,null
구룡포 하정,2025-02-20T15:00,fghe8,150000,null,11.100000,동해,null,null
고성 가진,2025-02-20T15:00,fggo3,150000,5.600000,6,동해,5.800000,null
양양,2025-02-20T15:00,byy87,150000,5.700000,5.800000,동해,5.800000,null
영덕,2025-02-20T15:00,byd8a,150000,11,11.200000,동해,11,null
삼척,2025-02-20T15:00,bsc87,150000,9.400000,10,동해,9.400000,null
나곡,2025-02-20T15:00,bngh3,150000,null,11.700000,동해,null,34.319000
고리,2025-02-20T15:00,bgrh3,150000,null,12,동해,null,35.160000
강릉,2025-02-20T15:00,bgna3,150000,6.300000,7.200000,동해,7.100000,null
덕천,2025-02-20T14:30,bdch3,143000,null,13.100000,동해,null,34.323000
구룡포 하정,2025-02-20T14:30,fghe8,143000,null,11.100000,동해,null,null
고성 가진,2025-02-20T14:30,fggo3,143000,5.600000,6,동해,5.800000,null
온양,2025-02-20T14:30,byyh3,143000,null,11.400000,동해,null,34.359000
양양,2025-02-20T14:30,byy87,143000,5.700000,5.800000,동해,5.800000,null
영덕,2025-02-20T14:30,byd8a,143000,11,11.200000,동해,11,null
삼척,2025-02-20T14:30,bsc87,143000,9.300000,10,동해,9.400000,null
나곡,2025-02-20T14:30,bngh3,143000,null,11.700000,동해,null,34.312000
진하,2025-02-20T14:30,bjhh3,143000,null,11.700000,동해,null,34.277000
고리,2025-02-20T14:30,bgrh3,143000,null,11.900000,동해,null,35.154000
강릉,2025-02-20T14:30,bgna3,143000,6.100000,7.200000,동해,7,null

In [383]:
df3.plot{
    x(obsDtm) { axis.name = "관측일시"}
    y(wtrTmp_1) {axis.name ="표층수온"}

    line{
        color(staNamKor){
            scale = continuous(Color.GREEN..Color.RED)
            legend{
                name = "관측소명"
            }
        }
    }

    layout {
        title = "관측지점별 해수 정보"
        size = 1200 to 500
    }
}

In [381]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE.csv")
staCodeDf

gru,code,name,isavailable,enddate,latitude,longitude
동해,bgj8a,기장,사용,2008-11-04,35.187000,129.227000
동해,byy87,양양,사용,2008-07-13,38.082700,128.698400
동해,byd8a,영덕,사용,2008-11-04,36.573700,129.437000
동해,bgna3,강릉,사용,2008-07-08,37.799000,128.949200
동해,bsc87,삼척,사용,2008-07-22,37.302300,129.312700
동해,fgbg3,고성 봉포,사용,2016-03-10,38.249400,128.624500
동해,fghe8,구룡포 하정,사용,2014-08-08,35.960700,129.549700
동해,bgjh3,기장(한수원),사용,2017-04-03,35.182500,129.235200
동해,bgrh3,고리,사용,2017-04-03,35.318600,129.314700
동해,bjhh3,진하,사용,2017-04-03,35.384700,129.368000
동해,bjjh3,정자,사용,2017-04-03,35.634700,129.495000
동해,bysh3,월성,사용,2017-04-03,35.717700,129.495000
동해,byph3,양포,사용,2017-04-03,35.865800,129.547200
동해,byyh3,온양,사용,2017-04-03,37.019400,129.425000
동해,bdch3,덕천,사용,2017-04-03,37.100000,129.404100
동해,bngh3,나곡,사용,2017-04-03,37.119100,129.395800
서해,br001,보령 효자도,사용,2005-10-05,36.415800,126.433300
서해,sj086,서산 지곡,사용,2008-06-21,36.893500,126.352400
서해,fbn69,백령도,사용,2006-09-12,37.950500,124.729500
서해,emp67,목포,사용,2006-07-03,34.789200,126.365300